"""Translation manager for multi-language support (I18N)."""

from __future__ import annotations

from PyQt6.QtCore import QObject, pyqtSignal

# ISO 639-1 / 3166 codes
LANGUAGES = {
    "en": "English",
    "zh_tw": "繁體中文",
    "zh_cn": "简体中文",
    "ja": "日本語",
    "ko": "한국어",
}

class Translator(QObject):
    """Global translation manager singleton."""

    language_changed = pyqtSignal()

    def __init__(self) -> None:
        super().__init__()
        self._current_lang = "en"  # Default

        # Define translations
        self._data = {
            "en": {
                "app.title": "Cyber Qin",
                "app.subtitle": "Cyber Qin Xian",
                "nav.live": "Live Mode",
                "nav.library": "Library",
                "nav.editor": "Sequencer",
                "sidebar.credit": "Edmond Virelle",
                "sidebar.ff14": "FF14: Aimant Virelle",
                "sidebar.wwm": "WWM: Ye Weiyu",
                "sidebar.vtuber": "VTuber: Edmond Virelle",
                "sidebar.support": "Support on Ko-fi",
                "sidebar.version": "v{version}",

                # Live Mode
                "live.title": "Live Mode",
                "live.desc": "Connect MIDI device and play in real-time.",
                "live.midi_device": "MIDI Device",
                "live.refresh": "Refresh",
                "live.connect": "Connect",
                "live.disconnect": "Disconnect",
                "live.mapping": "Mapping Scheme",
                "live.transpose": "Transpose",
                "live.auto_tune": "Auto-Tune",
                "live.record": "Record",
                "live.stop_record": "Stop Rec",
                "live.recording": "Recording...",
                "live.log": "Event Log",
                "live.status.connected": "Connected: {port}",
                "live.status.disconnected": "Disconnected",

                # Library
                "lib.title": "Library",
                "lib.desc": "Import MIDI files, double-click or press play to listen.",
                "lib.search": "Search tracks...",
                "lib.import": "+ Import MIDI",
                "lib.col.num": "#",
                "lib.col.title": "Title",
                "lib.col.duration": "Duration",
                "lib.empty.title": "No MIDI files imported",
                "lib.empty.sub": "Click '+ Import MIDI' to start",

                # Editor
                "editor.title": "Sequencer",
                "editor.desc": "Compose via piano keys or drag on timeline.",
                "editor.record": "● Record",
                "editor.play": "▶ Play",
                "editor.stop": "■ Stop",
                "editor.save": "Save",
                "editor.import": "Import",
                "editor.export": "Export",
                "editor.undo": "Undo (Ctrl+Z)",
                "editor.redo": "Redo (Ctrl+Y)",
                "editor.clear": "Clear All",
                "editor.pencil": "✎ Pencil",
                "editor.help": "Help",
                "editor.duration": "Duration",
                "editor.time_sig": "Time Sig",
                "editor.bpm": "BPM",
                "editor.snap": "Snap",
                "editor.velocity": "Velocity",
                "editor.shortcuts": "⌨ Shortcuts",
                "editor.note_count": "{notes} Notes · {bars} Bars",

                 # Now Playing
                "player.repeat.off": "Repeat Off",
                "player.repeat.one": "Repeat One",
                "player.repeat.all": "Repeat All",

                # Scheme names & descriptions
                "scheme.wwm_36.name": "Where Winds Meet 36-Key",
                "scheme.wwm_36.desc": "3×12 layout: ZXC / ASD / QWE rows, Shift/Ctrl for accidentals",
                "scheme.ff14_37.name": "FF14 37-Key",
                "scheme.ff14_37.desc": "3×12 Diatonic: Number(low) / QWER(mid) / ASDF(high), Ctrl=accidentals",
                "scheme.generic_24.name": "Generic 24-Key",
                "scheme.generic_24.desc": "2×12 layout: ZXC row + QWE row, Shift/Ctrl for accidentals",
                "scheme.generic_48.name": "Generic 48-Key",
                "scheme.generic_48.desc": "4×12 layout: Number / ZXC / ASD / QWE, 4 octaves",
                "scheme.generic_88.name": "Generic 88-Key",
                "scheme.generic_88.desc": "8×11 layout: layered Shift/Ctrl combos, full piano range",

                # Sort labels
                "lib.sort.default": "Default",
                "lib.sort.name": "Name",
                "lib.sort.bpm": "BPM",
                "lib.sort.notes": "Notes",
                "lib.sort.duration": "Duration",

                # Transpose suffix
                "live.transpose.suffix": " Octave",

                # Player bar
                "player.no_track": "No Track Loaded",
                "player.speed": "Speed",
                "player.countdown": "Get Ready... {n}",
                "player.switch_window": "Switch to game window",
                "player.play": "Play / Pause (Space)",
                "player.pause": "Pause",
                "player.stop": "Stop",
                "player.prev": "Previous (Ctrl+←)",
                "player.next": "Next (Ctrl+→)",
                "player.repeat.mode.off": "Repeat: Off",
                "player.repeat.mode.all": "Repeat: All",
                "player.repeat.mode.one": "Repeat: One",
            },
            "zh_tw": {
                "app.title": "賽博琴仙",
                "app.subtitle": "Cyber Qin Xian",
                "nav.live": "演奏模式",
                "nav.library": "曲庫",
                "nav.editor": "編曲器",
                "sidebar.credit": "Edmond Virelle",
                "sidebar.ff14": "FF14：艾曼維勒",
                "sidebar.wwm": "燕雲十六聲：葉微雨",
                "sidebar.vtuber": "VTuber: Edmond Virelle",
                "sidebar.support": "Support on Ko-fi",
                "sidebar.version": "v{version}",

                "live.title": "演奏模式",
                "live.desc": "連接 MIDI 裝置，即時演奏映射到遊戲按鍵。",
                "live.midi_device": "MIDI 裝置",
                "live.refresh": "重新整理",
                "live.connect": "連線",
                "live.disconnect": "斷線",
                "live.mapping": "映射方案",
                "live.transpose": "移調",
                "live.auto_tune": "自動校正",
                "live.record": "錄音",
                "live.stop_record": "停止錄音",
                "live.recording": "錄音中...",
                "live.log": "事件紀錄",
                "live.status.connected": "已連線: {port}",
                "live.status.disconnected": "未連線",

                "lib.title": "曲庫",
                "lib.desc": "匯入 MIDI 檔案，雙擊或按播放鍵自動演奏。",
                "lib.search": "搜尋曲目...",
                "lib.import": "+ 匯入 MIDI",
                "lib.col.num": "#",
                "lib.col.title": "標題",
                "lib.col.duration": "時長",
                "lib.empty.title": "尚未匯入任何 MIDI 檔案",
                "lib.empty.sub": "點擊「+ 匯入 MIDI」開始",

                "editor.title": "編曲器",
                "editor.desc": "點擊琴鍵輸入音符，拖曳時間軸編輯旋律。",
                "editor.record": "● 錄音",
                "editor.play": "▶ 播放",
                "editor.stop": "■ 停止",
                "editor.save": "存檔",
                "editor.import": "匯入",
                "editor.export": "匯出",
                "editor.undo": "復原 (Ctrl+Z)",
                "editor.redo": "重做 (Ctrl+Y)",
                "editor.clear": "清除全部",
                "editor.pencil": "✎ 鉛筆",
                "editor.help": "說明",
                "editor.duration": "時值",
                "editor.time_sig": "拍號",
                "editor.bpm": "BPM",
                "editor.snap": "Snap",
                "editor.velocity": "力度",
                "editor.shortcuts": "⌨ 快捷鍵",
                "editor.note_count": "{notes} 音符 · {bars} 小節",

                "player.repeat.off": "關閉",
                "player.repeat.one": "單曲重複",
                "player.repeat.all": "全部循環",

                "scheme.wwm_36.name": "燕雲十六聲 36鍵",
                "scheme.wwm_36.desc": "3×12 佈局：ZXC / ASD / QWE 行，Shift/Ctrl 修飾升降號",
                "scheme.ff14_37.name": "FF14 37鍵",
                "scheme.ff14_37.desc": "3×12 全音階：數字(低) / QWER(中) / ASDF(高)，Ctrl=升降",
                "scheme.generic_24.name": "通用 24鍵",
                "scheme.generic_24.desc": "2×12 佈局：ZXC 行 + QWE 行，Shift/Ctrl 修飾升降號",
                "scheme.generic_48.name": "通用 48鍵",
                "scheme.generic_48.desc": "4×12 佈局：數字行 / ZXC / ASD / QWE，4 個八度",
                "scheme.generic_88.name": "通用 88鍵",
                "scheme.generic_88.desc": "8×11 佈局：多層 Shift/Ctrl 組合，完整鋼琴範圍",

                "lib.sort.default": "預設順序",
                "lib.sort.name": "名稱",
                "lib.sort.bpm": "BPM",
                "lib.sort.notes": "音符數",
                "lib.sort.duration": "時長",

                "live.transpose.suffix": " 八度",

                "player.no_track": "未載入曲目",
                "player.speed": "速度",
                "player.countdown": "準備中... {n}",
                "player.switch_window": "切換到遊戲視窗",
                "player.play": "播放 / 暫停 (Space)",
                "player.pause": "暫停",
                "player.stop": "停止",
                "player.prev": "上一首 (Ctrl+←)",
                "player.next": "下一首 (Ctrl+→)",
                "player.repeat.mode.off": "循環模式: 關閉",
                "player.repeat.mode.all": "循環模式: 全部循環",
                "player.repeat.mode.one": "循環模式: 單曲重複",
            },
            "zh_cn": {
                "app.title": "赛博琴仙",
                "app.subtitle": "Cyber Qin Xian",
                "nav.live": "演奏模式",
                "nav.library": "曲库",
                "nav.editor": "编曲器",
                "sidebar.credit": "Edmond Virelle",
                "sidebar.ff14": "FF14：艾曼维勒",
                "sidebar.wwm": "燕云十六声：叶微雨",
                "sidebar.vtuber": "VTuber: Edmond Virelle",
                "sidebar.support": "Support on Ko-fi",
                "sidebar.version": "v{version}",

                "live.title": "演奏模式",
                "live.desc": "连接 MIDI 设备，即时演奏映射到游戏按键。",
                "live.midi_device": "MIDI 设备",
                "live.refresh": "刷新",
                "live.connect": "连接",
                "live.disconnect": "断开",
                "live.mapping": "映射方案",
                "live.transpose": "移调",
                "live.auto_tune": "自动校正",
                "live.record": "录音",
                "live.stop_record": "停止录音",
                "live.recording": "录音中...",
                "live.log": "事件记录",
                "live.status.connected": "已连接: {port}",
                "live.status.disconnected": "未连接",

                "lib.title": "曲库",
                "lib.desc": "导入 MIDI 文件，双击或按播放键自动演奏。",
                "lib.search": "搜索曲目...",
                "lib.import": "+ 导入 MIDI",
                "lib.col.num": "#",
                "lib.col.title": "标题",
                "lib.col.duration": "时长",
                "lib.empty.title": "尚未导入任何 MIDI 文件",
                "lib.empty.sub": "点击“+ 导入 MIDI”开始",

                "editor.title": "编曲器",
                "editor.desc": "点击琴键输入音符，拖拽时间轴编辑旋律。",
                "editor.record": "● 录音",
                "editor.play": "▶ 播放",
                "editor.stop": "■ 停止",
                "editor.save": "保存",
                "editor.import": "导入",
                "editor.export": "导出",
                "editor.undo": "撤销 (Ctrl+Z)",
                "editor.redo": "重做 (Ctrl+Y)",
                "editor.clear": "清除全部",
                "editor.pencil": "✎ 铅笔",
                "editor.help": "说明",
                "editor.duration": "时值",
                "editor.time_sig": "拍号",
                "editor.bpm": "BPM",
                "editor.snap": "Snap",
                "editor.velocity": "力度",
                "editor.shortcuts": "⌨ 快捷键",
                "editor.note_count": "{notes} 音符 · {bars} 小节",

                "player.repeat.off": "关闭",
                "player.repeat.one": "单曲重复",
                "player.repeat.all": "全部循环",

                "scheme.wwm_36.name": "燕云十六声 36键",
                "scheme.wwm_36.desc": "3×12 布局：ZXC / ASD / QWE 行，Shift/Ctrl 修饰升降号",
                "scheme.ff14_37.name": "FF14 37键",
                "scheme.ff14_37.desc": "3×12 全音阶：数字(低) / QWER(中) / ASDF(高)，Ctrl=升降",
                "scheme.generic_24.name": "通用 24键",
                "scheme.generic_24.desc": "2×12 布局：ZXC 行 + QWE 行，Shift/Ctrl 修饰升降号",
                "scheme.generic_48.name": "通用 48键",
                "scheme.generic_48.desc": "4×12 布局：数字行 / ZXC / ASD / QWE，4 个八度",
                "scheme.generic_88.name": "通用 88键",
                "scheme.generic_88.desc": "8×11 布局：多层 Shift/Ctrl 组合，完整钢琴范围",

                "lib.sort.default": "默认顺序",
                "lib.sort.name": "名称",
                "lib.sort.bpm": "BPM",
                "lib.sort.notes": "音符数",
                "lib.sort.duration": "时长",

                "live.transpose.suffix": " 八度",

                "player.no_track": "未载入曲目",
                "player.speed": "速度",
                "player.countdown": "准备中... {n}",
                "player.switch_window": "切换到游戏窗口",
                "player.play": "播放 / 暂停 (Space)",
                "player.pause": "暂停",
                "player.stop": "停止",
                "player.prev": "上一首 (Ctrl+←)",
                "player.next": "下一首 (Ctrl+→)",
                "player.repeat.mode.off": "循环模式: 关闭",
                "player.repeat.mode.all": "循环模式: 全部循环",
                "player.repeat.mode.one": "循环模式: 单曲重复",
            },
             "ja": {
                "app.title": "サイバー琴仙",
                "app.subtitle": "Cyber Qin Xian",
                "nav.live": "演奏モード",
                "nav.library": "ライブラリ",
                "nav.editor": "シーケンサー",
                "sidebar.credit": "Edmond Virelle",
                "sidebar.ff14": "FF14: Aimant Virelle",
                "sidebar.wwm": "燕雲十六声: 葉微雨",
                "sidebar.vtuber": "VTuber: Edmond Virelle",
                "sidebar.support": "Ko-fiでサポート",
                "sidebar.version": "v{version}",

                "live.title": "演奏モード",
                "live.desc": "MIDIデバイスを接続して、リアルタイムで演奏します。",
                "live.midi_device": "MIDIデバイス",
                "live.refresh": "更新",
                "live.connect": "接続",
                "live.disconnect": "切断",
                "live.mapping": "キー配置",
                "live.transpose": "移調",
                "live.auto_tune": "自動補正",
                "live.record": "録音",
                "live.stop_record": "録音停止",
                "live.recording": "録音中...",
                "live.log": "イベントログ",
                "live.status.connected": "接続済み: {port}",
                "live.status.disconnected": "未接続",

                "lib.title": "ライブラリ",
                "lib.desc": "MIDIファイルをインポートし、ダブルクリックまたは再生ボタンで演奏します。",
                "lib.search": "検索...",
                "lib.import": "+ MIDIインポート",
                "lib.col.num": "#",
                "lib.col.title": "タイトル",
                "lib.col.duration": "時間",
                "lib.empty.title": "MIDIファイルがありません",
                "lib.empty.sub": "「+ MIDIインポート」をクリックして開始",

                "editor.title": "シーケンサー",
                "editor.desc": "鍵盤をクリックして音符を入力、タイムラインで編集。",
                "editor.record": "● 録音",
                "editor.play": "▶ 再生",
                "editor.stop": "■ 停止",
                "editor.save": "保存",
                "editor.import": "インポート",
                "editor.export": "エクスポート",
                "editor.undo": "元に戻す (Ctrl+Z)",
                "editor.redo": "やり直し (Ctrl+Y)",
                "editor.clear": "全消去",
                "editor.pencil": "✎ 鉛筆",
                "editor.help": "ヘルプ",
                "editor.duration": "音価",
                "editor.time_sig": "拍子",
                "editor.bpm": "BPM",
                "editor.snap": "スナップ",
                "editor.velocity": "ベロシティ",
                "editor.shortcuts": "⌨ ショートカット",
                "editor.note_count": "{notes} 音符 · {bars} 小節",

                "player.repeat.off": "リピートオフ",
                "player.repeat.one": "1曲リピート",
                "player.repeat.all": "全曲リピート",

                "scheme.wwm_36.name": "燕雲十六声 36鍵",
                "scheme.wwm_36.desc": "3×12 配列：ZXC / ASD / QWE 行、Shift/Ctrl で変化記号",
                "scheme.ff14_37.name": "FF14 37鍵",
                "scheme.ff14_37.desc": "3×12 ダイアトニック：数字(低) / QWER(中) / ASDF(高)、Ctrl=変化記号",
                "scheme.generic_24.name": "汎用 24鍵",
                "scheme.generic_24.desc": "2×12 配列：ZXC 行 + QWE 行、Shift/Ctrl で変化記号",
                "scheme.generic_48.name": "汎用 48鍵",
                "scheme.generic_48.desc": "4×12 配列：数字行 / ZXC / ASD / QWE、4 オクターブ",
                "scheme.generic_88.name": "汎用 88鍵",
                "scheme.generic_88.desc": "8×11 配列：Shift/Ctrl 多層組合、フルピアノ範囲",

                "lib.sort.default": "デフォルト",
                "lib.sort.name": "名前",
                "lib.sort.bpm": "BPM",
                "lib.sort.notes": "音符数",
                "lib.sort.duration": "時間",

                "live.transpose.suffix": " オクターブ",

                "player.no_track": "トラック未読み込み",
                "player.speed": "速度",
                "player.countdown": "準備中... {n}",
                "player.switch_window": "ゲームウィンドウへ切替",
                "player.play": "再生 / 一時停止 (Space)",
                "player.pause": "一時停止",
                "player.stop": "停止",
                "player.prev": "前の曲 (Ctrl+←)",
                "player.next": "次の曲 (Ctrl+→)",
                "player.repeat.mode.off": "リピート: オフ",
                "player.repeat.mode.all": "リピート: 全曲",
                "player.repeat.mode.one": "リピート: 1曲",
            },
            "ko": {
                "app.title": "사이버 琴仙",
                "app.subtitle": "Cyber Qin Xian",
                "nav.live": "연주 모드",
                "nav.library": "라이브러리",
                "nav.editor": "시퀀서",
                "sidebar.credit": "Edmond Virelle",
                "sidebar.ff14": "FF14: Aimant Virelle",
                "sidebar.wwm": "연운십육성: 葉微雨",
                "sidebar.vtuber": "VTuber: Edmond Virelle",
                "sidebar.support": "Ko-fi 후원하기",
                "sidebar.version": "v{version}",

                "live.title": "연주 모드",
                "live.desc": "MIDI 장치를 연결하고 실시간으로 연주하세요.",
                "live.midi_device": "MIDI 장치",
                "live.refresh": "새로고침",
                "live.connect": "연결",
                "live.disconnect": "연결 끊기",
                "live.mapping": "키 매핑",
                "live.transpose": "조옮김",
                "live.auto_tune": "자동 보정",
                "live.record": "녹음",
                "live.stop_record": "녹음 중지",
                "live.recording": "녹음 중...",
                "live.log": "이벤트 로그",
                "live.status.connected": "연결됨: {port}",
                "live.status.disconnected": "연결 안 됨",

                "lib.title": "라이브러리",
                "lib.desc": "MIDI 파일을 가져오고 더블 클릭하거나 재생 버튼을 누르세요.",
                "lib.search": "검색...",
                "lib.import": "+ MIDI 가져오기",
                "lib.col.num": "#",
                "lib.col.title": "제목",
                "lib.col.duration": "시간",
                "lib.empty.title": "가져온 MIDI 파일 없음",
                "lib.empty.sub": "시작하려면 '+ MIDI 가져오기'를 클릭하세요",

                "editor.title": "시퀀서",
                "editor.desc": "피아노 건반을 클릭하여 음표 입력, 타임라인에서 편집.",
                "editor.record": "● 녹음",
                "editor.play": "▶ 재생",
                "editor.stop": "■ 정지",
                "editor.save": "저장",
                "editor.import": "가져오기",
                "editor.export": "내보내기",
                "editor.undo": "실행 취소 (Ctrl+Z)",
                "editor.redo": "다시 실행 (Ctrl+Y)",
                "editor.clear": "모두 지우기",
                "editor.pencil": "✎ 연필",
                "editor.help": "도움말",
                "editor.duration": "음표 길이",
                "editor.time_sig": "박자",
                "editor.bpm": "BPM",
                "editor.snap": "스냅",
                "editor.velocity": "벨로시티",
                "editor.shortcuts": "⌨ 단축키",
                "editor.note_count": "{notes} 음표 · {bars} 마디",

                "player.repeat.off": "반복 끔",
                "player.repeat.one": "한 곡 반복",
                "player.repeat.all": "전체 반복",

                "scheme.wwm_36.name": "연운십육성 36키",
                "scheme.wwm_36.desc": "3×12 배열: ZXC / ASD / QWE 행, Shift/Ctrl 로 변화표",
                "scheme.ff14_37.name": "FF14 37키",
                "scheme.ff14_37.desc": "3×12 다이어토닉: 숫자(저) / QWER(중) / ASDF(고), Ctrl=변화표",
                "scheme.generic_24.name": "범용 24키",
                "scheme.generic_24.desc": "2×12 배열: ZXC 행 + QWE 행, Shift/Ctrl 로 변화표",
                "scheme.generic_48.name": "범용 48키",
                "scheme.generic_48.desc": "4×12 배열: 숫자행 / ZXC / ASD / QWE, 4 옥타브",
                "scheme.generic_88.name": "범용 88키",
                "scheme.generic_88.desc": "8×11 배열: Shift/Ctrl 다층 조합, 풀 피아노 범위",

                "lib.sort.default": "기본 순서",
                "lib.sort.name": "이름",
                "lib.sort.bpm": "BPM",
                "lib.sort.notes": "음표 수",
                "lib.sort.duration": "시간",

                "live.transpose.suffix": " 옥타브",

                "player.no_track": "트랙 미로드",
                "player.speed": "속도",
                "player.countdown": "준비 중... {n}",
                "player.switch_window": "게임 창으로 전환",
                "player.play": "재생 / 일시정지 (Space)",
                "player.pause": "일시정지",
                "player.stop": "정지",
                "player.prev": "이전 곡 (Ctrl+←)",
                "player.next": "다음 곡 (Ctrl+→)",
                "player.repeat.mode.off": "반복: 끔",
                "player.repeat.mode.all": "반복: 전체",
                "player.repeat.mode.one": "반복: 한 곡",
            }
        }

    @property
    def current_language(self) -> str:
        return self._current_lang

    def set_language(self, lang_code: str) -> None:
        """Change current language and emit signal."""
        if lang_code in LANGUAGES and lang_code != self._current_lang:
            self._current_lang = lang_code
            self.language_changed.emit()

    def tr(self, key: str, **kwargs) -> str:
        """Translate key to current language. Returns key if not found."""
        lang_data = self._data.get(self._current_lang, {})
        text = lang_data.get(key)

        if text is None:
            # Fallback to English
            text = self._data.get("en", {}).get(key, key)

        try:
            return text.format(**kwargs)
        except (KeyError, ValueError):
            return text

# Global singleton instance
translator = Translator()
