"""Translation manager for multi-language support (I18N)."""

from __future__ import annotations

from PyQt6.QtCore import QObject, pyqtSignal

# ISO 639-1 / 3166 codes
LANGUAGES = {
    "en": "English",
    "zh_tw": "繁體中文",
    "zh_cn": "简体中文",
    "ja": "日本語",
    "ko": "한국어",
}


class Translator(QObject):
    """Global translation manager singleton."""

    language_changed = pyqtSignal()

    def __init__(self) -> None:
        super().__init__()
        self._current_lang = "en"  # Default

        # Define translations
        self._data = {
            "en": {
                "app.title": "Cyber Qin",
                "app.subtitle": "Cyber Qin Xian",
                "nav.live": "Live Mode",
                "nav.library": "Library",
                "nav.editor": "Sequencer",
                "sidebar.credit": "Edmond Virelle",
                "sidebar.ff14": "FF14: Aimant Virelle",
                "sidebar.wwm": "WWM: Ye Weiyu",
                "sidebar.vtuber": "VTuber: Edmond Virelle",
                "sidebar.support": "Support on Ko-fi",
                "sidebar.version": "v{version}",
                # Live Mode
                "live.title": "Live Mode",
                "live.desc": "Connect MIDI device and play in real-time.",
                "live.midi_device": "MIDI Device",
                "live.refresh": "Refresh",
                "live.connect": "Connect",
                "live.disconnect": "Disconnect",
                "live.mapping": "Mapping Scheme",
                "live.transpose": "Transpose",
                "live.auto_tune": "Auto-Tune",
                "live.record": "Record",
                "live.stop_record": "Stop Rec",
                "live.recording": "Recording...",
                "live.log": "Event Log",
                "live.status.connected": "Connected: {port}",
                "live.status.disconnected": "Disconnected",
                "live.view_mapping": "View Mapping",
                # Library
                "lib.title": "Library",
                "lib.desc": "Import MIDI files, double-click or press play to listen.",
                "lib.search": "Search tracks...",
                "lib.import": "+ Import MIDI",
                "lib.col.num": "#",
                "lib.col.title": "Title",
                "lib.col.duration": "Duration",
                "lib.empty.title": "No MIDI files imported",
                "lib.empty.sub": "Click '+ Import MIDI' to start",
                # Editor
                "editor.title": "Sequencer",
                "editor.desc": "Compose via piano keys or drag on timeline.",
                "editor.record": "● Record",
                "editor.play": "▶ Play",
                "editor.stop": "■ Stop",
                "editor.loop.tooltip": "Loop Playback (entire sequence)",
                "editor.metronome.tooltip": "Metronome Count-in (4 beats before playback)",
                "editor.save": "Save",
                "editor.import": "Import",
                "editor.export": "Export",
                "editor.undo": "Undo (Ctrl+Z)",
                "editor.redo": "Redo (Ctrl+Y)",
                "editor.clear": "Clear All",
                "editor.pencil": "✎ Pencil",
                "editor.help": "Help",
                "editor.duration": "Duration",
                "editor.time_sig": "Time Sig",
                "editor.bpm": "BPM",
                "editor.snap": "Snap",
                "editor.velocity": "Velocity",
                "editor.shortcuts": "⌨ Shortcuts",
                "editor.note_count": "{notes} Notes · {bars} Bars",
                # Now Playing
                "player.repeat.off": "Repeat Off",
                "player.repeat.one": "Repeat One",
                "player.repeat.all": "Repeat All",
                # Scheme names & descriptions
                "scheme.wwm_36.name": "Where Winds Meet 36-Key",
                "scheme.wwm_36.desc": "3×12 layout: ZXC / ASD / QWE rows, Shift/Ctrl for accidentals",
                "scheme.ff14_37.name": "FF14 37-Key",
                "scheme.ff14_37.desc": "3×12 Diatonic: Number(low) / QWER(mid) / ASDF(high), Ctrl=accidentals",
                "scheme.generic_24.name": "Generic 24-Key",
                "scheme.generic_24.desc": "2×12 layout: ZXC row + QWE row, Shift/Ctrl for accidentals",
                "scheme.generic_48.name": "Generic 48-Key",
                "scheme.generic_48.desc": "4×12 layout: Number / ZXC / ASD / QWE, 4 octaves",
                "scheme.generic_88.name": "Generic 88-Key",
                "scheme.generic_88.desc": "8×11 layout: layered Shift/Ctrl combos, full piano range",
                # Sort labels
                "lib.sort.default": "Default",
                "lib.sort.name": "Name",
                "lib.sort.bpm": "BPM",
                "lib.sort.notes": "Notes",
                "lib.sort.duration": "Duration",
                # Transpose suffix
                "live.transpose.suffix": " Octave",
                # Player bar
                "player.no_track": "No Track Loaded",
                "player.speed": "Speed",
                "player.countdown": "Get Ready... {n}",
                "player.switch_window": "Switch to game window",
                "player.play": "Play / Pause (Space)",
                "player.pause": "Pause",
                "player.stop": "Stop",
                "player.prev": "Previous (Ctrl+←)",
                "player.next": "Next (Ctrl+→)",
                "player.repeat.mode.off": "Repeat: Off",
                "player.repeat.mode.all": "Repeat: All",
                "player.repeat.mode.one": "Repeat: One",
                # Settings Dialog
                "settings.title": "Settings",
                "settings.tab.midi": "MIDI",
                "settings.tab.playback": "Playback",
                "settings.tab.editor": "Editor",
                "settings.tab.ui": "UI",
                "settings.tab.advanced": "Advanced",
                "settings.coming_soon": "(Coming Soon)",
                # MIDI Tab
                "settings.midi.device": "MIDI Device",
                "settings.midi.device.label": "Preferred Device",
                "settings.midi.device.none": "(None - Auto-detect)",
                "settings.midi.device.tooltip": "Select a preferred MIDI device to connect to on startup",
                "settings.midi.connection": "Connection",
                "settings.midi.auto_connect.label": "Auto-connect to last device on startup",
                "settings.midi.auto_connect.tooltip": "Automatically connect to the last used MIDI device when the app starts",
                # Playback Tab
                "settings.playback.transpose": "Transpose",
                "settings.playback.transpose.label": "Default Transpose",
                "settings.playback.transpose.semitones": "semitones",
                "settings.playback.transpose.tooltip": "Default transpose value for new MIDI files (in semitones, 12 = 1 octave)",
                # Editor Tab
                "settings.editor.snap": "Snap to Grid",
                "settings.editor.snap.enabled": "Enable snap to grid",
                "settings.editor.snap.tooltip": "Snap note placement and movement to grid lines",
                "settings.editor.grid": "Grid Subdivision",
                "settings.editor.note": "note",
                "settings.editor.autosave": "Auto-Save",
                "settings.editor.autosave.enabled": "Enable auto-save",
                "settings.editor.autosave.interval": "Interval",
                "settings.editor.seconds": "seconds",
                # UI Tab
                "settings.ui.language": "Language",
                "settings.ui.language.label": "Interface Language",
                "settings.ui.language.auto": "Auto (System)",
                "settings.ui.theme": "Theme",
                "settings.ui.theme.label": "Color Theme",
                "settings.ui.theme.dark": "Dark (賽博墨韻)",
                "settings.ui.theme.light": "Light",
                # Advanced Tab
                "settings.advanced.config_location": "Configuration file location:",
                # Key Mapping Viewer
                "mapping_viewer.title": "Key Mapping Viewer",
                "mapping_viewer.keys": "keys",
                "mapping_viewer.midi_note": "MIDI Note",
                "mapping_viewer.note_name": "Note Name",
                "mapping_viewer.keyboard_key": "Keyboard Key",
                "mapping_viewer.modifier": "Modifier",
                "mapping_viewer.none": "None",
                "editor.pause": "\u23f8 Pause",
                "editor.resume": "\u25b6 Resume",
                # New features
                "editor.arrange": "Arrange",
                "editor.fx": "FX",
                "editor.fx.label": "\u2728 FX",
                "editor.fx.tooltip": "MIDI FX: Arpeggiator, Humanize, Quantize, Chords",
                "editor.generate": "Generate",
                "editor.generate.label": "\ud83c\udfb2 Generate",
                "editor.generate.tooltip": "AI Compose: Generate melody and bass lines",
                "editor.sidebar.tooltip": "Toggle Sidebar: Hide/show track panel and pitch ruler",
                "editor.ghost": "Ghost",
                "editor.automation": "Automation",
                "editor.score": "Score",
                "nav.practice": "Practice",
                "practice.title": "Practice Mode",
                "practice.desc": "Select a track from the Library, then click 'Practice' to begin. Notes fall from above — press the correct key at the gold line to score points.",
                "practice.score": "Score",
                "practice.accuracy": "Accuracy",
                "practice.combo": "Combo",
                "practice.perfect": "Perfect",
                "practice.great": "Great",
                "practice.good": "Good",
                "practice.miss": "Miss",
                "practice.start": "Start Practice",
                "practice.stop": "Stop",
                "practice.result": "Results",
                "practice.max_combo": "Max Combo",
                "practice.mode.midi": "MIDI Keyboard",
                "practice.mode.keyboard": "Computer Keyboard",
                "practice.scheme": "Key Layout",
                "live.visualizer": "Visualizer",
                "lib.metadata.title": "Track Metadata",
                "lib.metadata.edit": "Edit Metadata",
                "lib.export_bundle": "Export Bundle",
                "lib.import_bundle": "Import Bundle",
                "lib.practice": "Practice",
                "lib.play": "Play",
                "lib.edit": "Edit in Sequencer",
                "lib.remove": "Remove",
                "lib.col.artist": "Artist",
                "lib.col.game": "Game",
                "lib.col.difficulty": "Difficulty",
                # FX Dialog
                "fx.tab.arp": "Arpeggiator",
                "fx.tab.humanize": "Humanize",
                "fx.tab.quantize": "Quantize",
                "fx.tab.chords": "Chords",
                "fx.arp.pattern": "Pattern:",
                "fx.arp.rate": "Rate (beats):",
                "fx.arp.octave": "Octave Range:",
                "fx.arp.gate": "Gate:",
                "fx.hum.timing": "Timing Jitter (beats):",
                "fx.hum.velocity": "Velocity Jitter:",
                "fx.hum.duration": "Duration Jitter (beats):",
                "fx.q.grid": "Grid (beats):",
                "fx.q.strength": "Strength:",
                "fx.chord.type": "Chord Type:",
                "fx.chord.voicing": "Voicing:",
                "fx.chord.vel_scale": "Velocity Scale:",
                "fx.apply": "Apply",
                "fx.cancel": "Cancel",
                # Melody Dialog
                "gen.tab.melody": "Melody",
                "gen.tab.bass": "Bass Line",
                "gen.root": "Root Note:",
                "gen.scale": "Scale:",
                "gen.bars": "Bars:",
                "gen.note_range": "Note Range:",
                "gen.to": "to",
                "gen.stepwise_bias": "Stepwise Bias:",
                "gen.velocity": "Velocity:",
                "gen.seed": "Seed:",
                "gen.random": "Random",
                "gen.progression": "Progression:",
                "gen.pattern": "Pattern:",
                "gen.track": "Track:",
                "gen.generate": "Generate",
                "gen.cancel": "Cancel",
            },
            "zh_tw": {
                "app.title": "賽博琴仙",
                "app.subtitle": "Cyber Qin Xian",
                "nav.live": "演奏模式",
                "nav.library": "曲庫",
                "nav.editor": "編曲器",
                "sidebar.credit": "Edmond Virelle",
                "sidebar.ff14": "FF14：艾曼維勒",
                "sidebar.wwm": "燕雲十六聲：葉微雨",
                "sidebar.vtuber": "VTuber: Edmond Virelle",
                "sidebar.support": "Support on Ko-fi",
                "sidebar.version": "v{version}",
                "live.title": "演奏模式",
                "live.desc": "連接 MIDI 裝置，即時演奏映射到遊戲按鍵。",
                "live.midi_device": "MIDI 裝置",
                "live.refresh": "重新整理",
                "live.connect": "連線",
                "live.disconnect": "斷線",
                "live.mapping": "映射方案",
                "live.transpose": "移調",
                "live.auto_tune": "自動校正",
                "live.record": "錄音",
                "live.stop_record": "停止錄音",
                "live.recording": "錄音中...",
                "live.log": "事件紀錄",
                "live.status.connected": "已連線: {port}",
                "live.status.disconnected": "未連線",
                "live.view_mapping": "查看映射",
                "lib.title": "曲庫",
                "lib.desc": "匯入 MIDI 檔案，雙擊或按播放鍵自動演奏。",
                "lib.search": "搜尋曲目...",
                "lib.import": "+ 匯入 MIDI",
                "lib.col.num": "#",
                "lib.col.title": "標題",
                "lib.col.duration": "時長",
                "lib.empty.title": "尚未匯入任何 MIDI 檔案",
                "lib.empty.sub": "點擊「+ 匯入 MIDI」開始",
                "editor.title": "編曲器",
                "editor.desc": "點擊琴鍵輸入音符，拖曳時間軸編輯旋律。",
                "editor.record": "● 錄音",
                "editor.play": "▶ 播放",
                "editor.stop": "■ 停止",
                "editor.loop.tooltip": "循環播放（全曲循環）",
                "editor.metronome.tooltip": "節拍器預備拍（播放前 4 拍倒數）",
                "editor.save": "存檔",
                "editor.import": "匯入",
                "editor.export": "匯出",
                "editor.undo": "復原 (Ctrl+Z)",
                "editor.redo": "重做 (Ctrl+Y)",
                "editor.clear": "清除全部",
                "editor.pencil": "✎ 鉛筆",
                "editor.help": "說明",
                "editor.duration": "時值",
                "editor.time_sig": "拍號",
                "editor.bpm": "BPM",
                "editor.snap": "Snap",
                "editor.velocity": "力度",
                "editor.shortcuts": "⌨ 快捷鍵",
                "editor.note_count": "{notes} 音符 · {bars} 小節",
                "player.repeat.off": "關閉",
                "player.repeat.one": "單曲重複",
                "player.repeat.all": "全部循環",
                "scheme.wwm_36.name": "燕雲十六聲 36鍵",
                "scheme.wwm_36.desc": "3×12 佈局：ZXC / ASD / QWE 行，Shift/Ctrl 修飾升降號",
                "scheme.ff14_37.name": "FF14 37鍵",
                "scheme.ff14_37.desc": "3×12 全音階：數字(低) / QWER(中) / ASDF(高)，Ctrl=升降",
                "scheme.generic_24.name": "通用 24鍵",
                "scheme.generic_24.desc": "2×12 佈局：ZXC 行 + QWE 行，Shift/Ctrl 修飾升降號",
                "scheme.generic_48.name": "通用 48鍵",
                "scheme.generic_48.desc": "4×12 佈局：數字行 / ZXC / ASD / QWE，4 個八度",
                "scheme.generic_88.name": "通用 88鍵",
                "scheme.generic_88.desc": "8×11 佈局：多層 Shift/Ctrl 組合，完整鋼琴範圍",
                "lib.sort.default": "預設順序",
                "lib.sort.name": "名稱",
                "lib.sort.bpm": "BPM",
                "lib.sort.notes": "音符數",
                "lib.sort.duration": "時長",
                "live.transpose.suffix": " 八度",
                "player.no_track": "未載入曲目",
                "player.speed": "速度",
                "player.countdown": "準備中... {n}",
                "player.switch_window": "切換到遊戲視窗",
                "player.play": "播放 / 暫停 (Space)",
                "player.pause": "暫停",
                "player.stop": "停止",
                "player.prev": "上一首 (Ctrl+←)",
                "player.next": "下一首 (Ctrl+→)",
                "player.repeat.mode.off": "循環模式: 關閉",
                "player.repeat.mode.all": "循環模式: 全部循環",
                "player.repeat.mode.one": "循環模式: 單曲重複",
                # Settings Dialog
                "settings.title": "設定",
                "settings.tab.midi": "MIDI",
                "settings.tab.playback": "播放",
                "settings.tab.editor": "編輯器",
                "settings.tab.ui": "介面",
                "settings.tab.advanced": "進階",
                "settings.coming_soon": "(即將推出)",
                # MIDI Tab
                "settings.midi.device": "MIDI 裝置",
                "settings.midi.device.label": "偏好裝置",
                "settings.midi.device.none": "(無 - 自動偵測)",
                "settings.midi.device.tooltip": "選擇啟動時要連線的偏好 MIDI 裝置",
                "settings.midi.connection": "連線",
                "settings.midi.auto_connect.label": "啟動時自動連線到最後使用的裝置",
                "settings.midi.auto_connect.tooltip": "應用程式啟動時自動連線到上次使用的 MIDI 裝置",
                # Playback Tab
                "settings.playback.transpose": "移調",
                "settings.playback.transpose.label": "預設移調",
                "settings.playback.transpose.semitones": "半音",
                "settings.playback.transpose.tooltip": "新 MIDI 檔案的預設移調值 (以半音為單位，12 = 1 個八度)",
                # Editor Tab
                "settings.editor.snap": "對齊網格",
                "settings.editor.snap.enabled": "啟用對齊網格",
                "settings.editor.snap.tooltip": "將音符放置和移動對齊到網格線",
                "settings.editor.grid": "網格細分",
                "settings.editor.note": "音符",
                "settings.editor.autosave": "自動儲存",
                "settings.editor.autosave.enabled": "啟用自動儲存",
                "settings.editor.autosave.interval": "間隔",
                "settings.editor.seconds": "秒",
                # UI Tab
                "settings.ui.language": "語言",
                "settings.ui.language.label": "介面語言",
                "settings.ui.language.auto": "自動 (系統)",
                "settings.ui.theme": "主題",
                "settings.ui.theme.label": "色彩主題",
                "settings.ui.theme.dark": "深色 (賽博墨韻)",
                "settings.ui.theme.light": "淺色",
                # Advanced Tab
                "settings.advanced.config_location": "設定檔位置：",
                # Key Mapping Viewer
                "mapping_viewer.title": "按鍵映射查看器",
                "mapping_viewer.keys": "個鍵",
                "mapping_viewer.midi_note": "MIDI 音符",
                "mapping_viewer.note_name": "音符名稱",
                "mapping_viewer.keyboard_key": "鍵盤按鍵",
                "mapping_viewer.modifier": "修飾鍵",
                "mapping_viewer.none": "無",
                "editor.pause": "\u23f8 暫停",
                "editor.resume": "\u25b6 繼續",
                # New features
                "editor.arrange": "智能編排",
                "editor.fx": "效果",
                "editor.fx.label": "\u2728 效果",
                "editor.fx.tooltip": "MIDI 效果：琶音器、人性化、量化、和弦生成",
                "editor.generate": "生成",
                "editor.generate.label": "\ud83c\udfb2 生成",
                "editor.generate.tooltip": "AI 作曲：自動生成旋律與低音線",
                "editor.sidebar.tooltip": "切換側邊欄：隱藏/顯示音軌面板和音高尺規",
                "editor.ghost": "幽靈",
                "editor.automation": "自動化",
                "editor.score": "樂譜",
                "nav.practice": "練習",
                "practice.title": "練習模式",
                "practice.desc": "從曲庫選擇一首曲目，點擊「練習」按鈕開始。音符會從上方落下，在金線處準確按鍵即可得分。",
                "practice.score": "分數",
                "practice.accuracy": "準確率",
                "practice.combo": "連擊",
                "practice.perfect": "完美",
                "practice.great": "優秀",
                "practice.good": "良好",
                "practice.miss": "失誤",
                "practice.start": "開始練習",
                "practice.stop": "停止",
                "practice.result": "成績",
                "practice.max_combo": "最高連擊",
                "practice.mode.midi": "MIDI 鍵盤",
                "practice.mode.keyboard": "電腦鍵盤",
                "practice.scheme": "鍵位方案",
                "live.visualizer": "視覺化",
                "lib.metadata.title": "曲目資訊",
                "lib.metadata.edit": "編輯資訊",
                "lib.export_bundle": "匯出合集",
                "lib.import_bundle": "匯入合集",
                "lib.practice": "練習",
                "lib.play": "播放",
                "lib.edit": "在編曲器中編輯",
                "lib.remove": "移除",
                "lib.col.artist": "演奏者",
                "lib.col.game": "遊戲",
                "lib.col.difficulty": "難度",
                # FX Dialog
                "fx.tab.arp": "琶音器",
                "fx.tab.humanize": "人性化",
                "fx.tab.quantize": "量化",
                "fx.tab.chords": "和弦",
                "fx.arp.pattern": "模式:",
                "fx.arp.rate": "速率 (拍):",
                "fx.arp.octave": "八度範圍:",
                "fx.arp.gate": "門限:",
                "fx.hum.timing": "時值搖擺 (拍):",
                "fx.hum.velocity": "力度搖擺:",
                "fx.hum.duration": "時長搖擺 (拍):",
                "fx.q.grid": "網格 (拍):",
                "fx.q.strength": "強度:",
                "fx.chord.type": "和弦類型:",
                "fx.chord.voicing": "聲位:",
                "fx.chord.vel_scale": "力度比例:",
                "fx.apply": "套用",
                "fx.cancel": "取消",
                # Melody Dialog
                "gen.tab.melody": "旋律",
                "gen.tab.bass": "低音線",
                "gen.root": "根音:",
                "gen.scale": "音階:",
                "gen.bars": "小節:",
                "gen.note_range": "音域:",
                "gen.to": "至",
                "gen.stepwise_bias": "級進偏好:",
                "gen.velocity": "力度:",
                "gen.seed": "種子:",
                "gen.random": "隨機",
                "gen.progression": "和聲進行:",
                "gen.pattern": "模式:",
                "gen.track": "音軌:",
                "gen.generate": "生成",
                "gen.cancel": "取消",
            },
            "zh_cn": {
                "app.title": "赛博琴仙",
                "app.subtitle": "Cyber Qin Xian",
                "nav.live": "演奏模式",
                "nav.library": "曲库",
                "nav.editor": "编曲器",
                "sidebar.credit": "Edmond Virelle",
                "sidebar.ff14": "FF14：艾曼维勒",
                "sidebar.wwm": "燕云十六声：叶微雨",
                "sidebar.vtuber": "VTuber: Edmond Virelle",
                "sidebar.support": "Support on Ko-fi",
                "sidebar.version": "v{version}",
                "live.title": "演奏模式",
                "live.desc": "连接 MIDI 设备，即时演奏映射到游戏按键。",
                "live.midi_device": "MIDI 设备",
                "live.refresh": "刷新",
                "live.connect": "连接",
                "live.disconnect": "断开",
                "live.mapping": "映射方案",
                "live.transpose": "移调",
                "live.auto_tune": "自动校正",
                "live.record": "录音",
                "live.stop_record": "停止录音",
                "live.recording": "录音中...",
                "live.log": "事件记录",
                "live.status.connected": "已连接: {port}",
                "live.status.disconnected": "未连接",
                "live.view_mapping": "查看映射",
                "lib.title": "曲库",
                "lib.desc": "导入 MIDI 文件，双击或按播放键自动演奏。",
                "lib.search": "搜索曲目...",
                "lib.import": "+ 导入 MIDI",
                "lib.col.num": "#",
                "lib.col.title": "标题",
                "lib.col.duration": "时长",
                "lib.empty.title": "尚未导入任何 MIDI 文件",
                "lib.empty.sub": "点击“+ 导入 MIDI”开始",
                "editor.title": "编曲器",
                "editor.desc": "点击琴键输入音符，拖拽时间轴编辑旋律。",
                "editor.record": "● 录音",
                "editor.play": "▶ 播放",
                "editor.stop": "■ 停止",
                "editor.loop.tooltip": "循环播放（全曲循环）",
                "editor.metronome.tooltip": "节拍器预备拍（播放前 4 拍倒数）",
                "editor.save": "保存",
                "editor.import": "导入",
                "editor.export": "导出",
                "editor.undo": "撤销 (Ctrl+Z)",
                "editor.redo": "重做 (Ctrl+Y)",
                "editor.clear": "清除全部",
                "editor.pencil": "✎ 铅笔",
                "editor.help": "说明",
                "editor.duration": "时值",
                "editor.time_sig": "拍号",
                "editor.bpm": "BPM",
                "editor.snap": "Snap",
                "editor.velocity": "力度",
                "editor.shortcuts": "⌨ 快捷键",
                "editor.note_count": "{notes} 音符 · {bars} 小节",
                "player.repeat.off": "关闭",
                "player.repeat.one": "单曲重复",
                "player.repeat.all": "全部循环",
                "scheme.wwm_36.name": "燕云十六声 36键",
                "scheme.wwm_36.desc": "3×12 布局：ZXC / ASD / QWE 行，Shift/Ctrl 修饰升降号",
                "scheme.ff14_37.name": "FF14 37键",
                "scheme.ff14_37.desc": "3×12 全音阶：数字(低) / QWER(中) / ASDF(高)，Ctrl=升降",
                "scheme.generic_24.name": "通用 24键",
                "scheme.generic_24.desc": "2×12 布局：ZXC 行 + QWE 行，Shift/Ctrl 修饰升降号",
                "scheme.generic_48.name": "通用 48键",
                "scheme.generic_48.desc": "4×12 布局：数字行 / ZXC / ASD / QWE，4 个八度",
                "scheme.generic_88.name": "通用 88键",
                "scheme.generic_88.desc": "8×11 布局：多层 Shift/Ctrl 组合，完整钢琴范围",
                "lib.sort.default": "默认顺序",
                "lib.sort.name": "名称",
                "lib.sort.bpm": "BPM",
                "lib.sort.notes": "音符数",
                "lib.sort.duration": "时长",
                "live.transpose.suffix": " 八度",
                "player.no_track": "未载入曲目",
                "player.speed": "速度",
                "player.countdown": "准备中... {n}",
                "player.switch_window": "切换到游戏窗口",
                "player.play": "播放 / 暂停 (Space)",
                "player.pause": "暂停",
                "player.stop": "停止",
                "player.prev": "上一首 (Ctrl+←)",
                "player.next": "下一首 (Ctrl+→)",
                "player.repeat.mode.off": "循环模式: 关闭",
                "player.repeat.mode.all": "循环模式: 全部循环",
                "player.repeat.mode.one": "循环模式: 单曲重复",
                # Settings Dialog
                "settings.title": "设置",
                "settings.tab.midi": "MIDI",
                "settings.tab.playback": "播放",
                "settings.tab.editor": "编辑器",
                "settings.tab.ui": "界面",
                "settings.tab.advanced": "高级",
                "settings.coming_soon": "(即将推出)",
                # MIDI Tab
                "settings.midi.device": "MIDI 设备",
                "settings.midi.device.label": "首选设备",
                "settings.midi.device.none": "(无 - 自动检测)",
                "settings.midi.device.tooltip": "选择启动时要连接的首选 MIDI 设备",
                "settings.midi.connection": "连接",
                "settings.midi.auto_connect.label": "启动时自动连接到最后使用的设备",
                "settings.midi.auto_connect.tooltip": "应用程序启动时自动连接到上次使用的 MIDI 设备",
                # Playback Tab
                "settings.playback.transpose": "移调",
                "settings.playback.transpose.label": "默认移调",
                "settings.playback.transpose.semitones": "半音",
                "settings.playback.transpose.tooltip": "新 MIDI 文件的默认移调值 (以半音为单位，12 = 1 个八度)",
                # Editor Tab
                "settings.editor.snap": "对齐网格",
                "settings.editor.snap.enabled": "启用对齐网格",
                "settings.editor.snap.tooltip": "将音符放置和移动对齐到网格线",
                "settings.editor.grid": "网格细分",
                "settings.editor.note": "音符",
                "settings.editor.autosave": "自动保存",
                "settings.editor.autosave.enabled": "启用自动保存",
                "settings.editor.autosave.interval": "间隔",
                "settings.editor.seconds": "秒",
                # UI Tab
                "settings.ui.language": "语言",
                "settings.ui.language.label": "界面语言",
                "settings.ui.language.auto": "自动 (系统)",
                "settings.ui.theme": "主题",
                "settings.ui.theme.label": "颜色主题",
                "settings.ui.theme.dark": "深色 (赛博墨韵)",
                "settings.ui.theme.light": "浅色",
                # Advanced Tab
                "settings.advanced.config_location": "配置文件位置：",
                # Key Mapping Viewer
                "mapping_viewer.title": "按键映射查看器",
                "mapping_viewer.keys": "个键",
                "mapping_viewer.midi_note": "MIDI 音符",
                "mapping_viewer.note_name": "音符名称",
                "mapping_viewer.keyboard_key": "键盘按键",
                "mapping_viewer.modifier": "修饰键",
                "mapping_viewer.none": "无",
                "editor.pause": "\u23f8 暂停",
                "editor.resume": "\u25b6 继续",
                # New features
                "editor.arrange": "智能编排",
                "editor.fx": "效果",
                "editor.fx.label": "\u2728 效果",
                "editor.fx.tooltip": "MIDI 效果：琶音器、人性化、量化、和弦生成",
                "editor.generate": "生成",
                "editor.generate.label": "\ud83c\udfb2 生成",
                "editor.generate.tooltip": "AI 作曲：自动生成旋律与低音线",
                "editor.sidebar.tooltip": "切换侧边栏：隐藏/显示音轨面板和音高尺规",
                "editor.ghost": "幽灵",
                "editor.automation": "自动化",
                "editor.score": "乐谱",
                "nav.practice": "练习",
                "practice.title": "练习模式",
                "practice.desc": "从曲库选择一首曲目，点击「练习」按钮开始。音符会从上方落下，在金线处准确按键即可得分。",
                "practice.score": "分数",
                "practice.accuracy": "准确率",
                "practice.combo": "连击",
                "practice.perfect": "完美",
                "practice.great": "优秀",
                "practice.good": "良好",
                "practice.miss": "失误",
                "practice.start": "开始练习",
                "practice.stop": "停止",
                "practice.result": "成绩",
                "practice.max_combo": "最高连击",
                "practice.mode.midi": "MIDI 键盘",
                "practice.mode.keyboard": "电脑键盘",
                "practice.scheme": "键位方案",
                "live.visualizer": "可视化",
                "lib.metadata.title": "曲目信息",
                "lib.metadata.edit": "编辑信息",
                "lib.export_bundle": "导出合集",
                "lib.import_bundle": "导入合集",
                "lib.practice": "练习",
                "lib.play": "播放",
                "lib.edit": "在编曲器中编辑",
                "lib.remove": "移除",
                "lib.col.artist": "演奏者",
                "lib.col.game": "游戏",
                "lib.col.difficulty": "难度",
                # FX Dialog
                "fx.tab.arp": "琶音器",
                "fx.tab.humanize": "人性化",
                "fx.tab.quantize": "量化",
                "fx.tab.chords": "和弦",
                "fx.arp.pattern": "模式:",
                "fx.arp.rate": "速率 (拍):",
                "fx.arp.octave": "八度范围:",
                "fx.arp.gate": "门限:",
                "fx.hum.timing": "时值摇摆 (拍):",
                "fx.hum.velocity": "力度摇摆:",
                "fx.hum.duration": "時長搖擺 (拍):",
                "fx.q.grid": "网格 (拍):",
                "fx.q.strength": "强度:",
                "fx.chord.type": "和弦类型:",
                "fx.chord.voicing": "声位:",
                "fx.chord.vel_scale": "力度比例:",
                "fx.apply": "应用",
                "fx.cancel": "取消",
                # Melody Dialog
                "gen.tab.melody": "旋律",
                "gen.tab.bass": "低音线",
                "gen.root": "根音:",
                "gen.scale": "音阶:",
                "gen.bars": "小节:",
                "gen.note_range": "音域:",
                "gen.to": "至",
                "gen.stepwise_bias": "级进偏好:",
                "gen.velocity": "力度:",
                "gen.seed": "种子:",
                "gen.random": "随机",
                "gen.progression": "和声进行:",
                "gen.pattern": "模式:",
                "gen.track": "音轨:",
                "gen.generate": "生成",
                "gen.cancel": "取消",
            },
            "ja": {
                "app.title": "サイバー琴仙",
                "app.subtitle": "Cyber Qin Xian",
                "nav.live": "演奏モード",
                "nav.library": "ライブラリ",
                "nav.editor": "シーケンサー",
                "sidebar.credit": "Edmond Virelle",
                "sidebar.ff14": "FF14: Aimant Virelle",
                "sidebar.wwm": "燕雲十六声: 葉微雨",
                "sidebar.vtuber": "VTuber: Edmond Virelle",
                "sidebar.support": "Ko-fiでサポート",
                "sidebar.version": "v{version}",
                "live.title": "演奏モード",
                "live.desc": "MIDIデバイスを接続して、リアルタイムで演奏します。",
                "live.midi_device": "MIDIデバイス",
                "live.refresh": "更新",
                "live.connect": "接続",
                "live.disconnect": "切断",
                "live.mapping": "キー配置",
                "live.transpose": "移調",
                "live.auto_tune": "自動補正",
                "live.record": "録音",
                "live.stop_record": "録音停止",
                "live.recording": "録音中...",
                "live.log": "イベントログ",
                "live.status.connected": "接続済み: {port}",
                "live.status.disconnected": "未接続",
                "lib.title": "ライブラリ",
                "lib.desc": "MIDIファイルをインポートし、ダブルクリックまたは再生ボタンで演奏します。",
                "lib.search": "検索...",
                "lib.import": "+ MIDIインポート",
                "lib.col.num": "#",
                "lib.col.title": "タイトル",
                "lib.col.duration": "時間",
                "lib.empty.title": "MIDIファイルがありません",
                "lib.empty.sub": "「+ MIDIインポート」をクリックして開始",
                "editor.title": "シーケンサー",
                "editor.desc": "鍵盤をクリックして音符を入力、タイムラインで編集。",
                "editor.record": "● 録音",
                "editor.play": "▶ 再生",
                "editor.stop": "■ 停止",
                "editor.save": "保存",
                "editor.import": "インポート",
                "editor.export": "エクスポート",
                "editor.undo": "元に戻す (Ctrl+Z)",
                "editor.redo": "やり直し (Ctrl+Y)",
                "editor.clear": "全消去",
                "editor.pencil": "✎ 鉛筆",
                "editor.help": "ヘルプ",
                "editor.duration": "音価",
                "editor.time_sig": "拍子",
                "editor.bpm": "BPM",
                "editor.snap": "スナップ",
                "editor.velocity": "ベロシティ",
                "editor.shortcuts": "⌨ ショートカット",
                "editor.note_count": "{notes} 音符 · {bars} 小節",
                "player.repeat.off": "リピートオフ",
                "player.repeat.one": "1曲リピート",
                "player.repeat.all": "全曲リピート",
                "scheme.wwm_36.name": "燕雲十六声 36鍵",
                "scheme.wwm_36.desc": "3×12 配列：ZXC / ASD / QWE 行、Shift/Ctrl で変化記号",
                "scheme.ff14_37.name": "FF14 37鍵",
                "scheme.ff14_37.desc": "3×12 ダイアトニック：数字(低) / QWER(中) / ASDF(高)、Ctrl=変化記号",
                "scheme.generic_24.name": "汎用 24鍵",
                "scheme.generic_24.desc": "2×12 配列：ZXC 行 + QWE 行、Shift/Ctrl で変化記号",
                "scheme.generic_48.name": "汎用 48鍵",
                "scheme.generic_48.desc": "4×12 配列：数字行 / ZXC / ASD / QWE、4 オクターブ",
                "scheme.generic_88.name": "汎用 88鍵",
                "scheme.generic_88.desc": "8×11 配列：Shift/Ctrl 多層組合、フルピアノ範囲",
                "lib.sort.default": "デフォルト",
                "lib.sort.name": "名前",
                "lib.sort.bpm": "BPM",
                "lib.sort.notes": "音符数",
                "lib.sort.duration": "時間",
                "live.transpose.suffix": " オクターブ",
                "player.no_track": "トラック未読み込み",
                "player.speed": "速度",
                "player.countdown": "準備中... {n}",
                "player.switch_window": "ゲームウィンドウへ切替",
                "player.play": "再生 / 一時停止 (Space)",
                "player.pause": "一時停止",
                "player.stop": "停止",
                "player.prev": "前の曲 (Ctrl+←)",
                "player.next": "次の曲 (Ctrl+→)",
                "player.repeat.mode.off": "リピート: オフ",
                "player.repeat.mode.all": "リピート: 全曲",
                "player.repeat.mode.one": "リピート: 1曲",
                "editor.pause": "\u23f8 一時停止",
                "editor.resume": "\u25b6 再開",
                # New features
                "editor.arrange": "アレンジ",
                "editor.fx": "エフェクト",
                "editor.fx.label": "\u2728 エフェクト",
                "editor.fx.tooltip": "MIDIエフェクト：アルペジエーター、ヒューマナイズ、クオンタイズ、コード生成",
                "editor.generate": "生成",
                "editor.generate.label": "\ud83c\udfb2 生成",
                "editor.generate.tooltip": "AI作曲：メロディとベースラインを自動生成",
                "editor.sidebar.tooltip": "サイドバー切替：トラックパネルとピッチルーラーの表示/非表示",
                "editor.ghost": "ゴースト",
                "editor.automation": "オートメーション",
                "editor.score": "楽譜",
                "nav.practice": "練習",
                "practice.title": "練習モード",
                "practice.desc": "ライブラリから曲を選び「練習」ボタンをクリック。上から音符が降ってくるので、金線のタイミングで正確にキーを押してスコアを獲得しましょう。",
                "practice.score": "スコア",
                "practice.accuracy": "正確率",
                "practice.combo": "コンボ",
                "practice.start": "練習開始",
                "practice.stop": "停止",
                "practice.mode.midi": "MIDIキーボード",
                "practice.mode.keyboard": "PCキーボード",
                "practice.scheme": "キー配置",
                "live.visualizer": "ビジュアライザー",
                "lib.metadata.title": "トラック情報",
                "lib.practice": "練習",
                "lib.play": "再生",
                "lib.edit": "シーケンサーで編集",
                "lib.remove": "削除",
                # FX Dialog
                "fx.tab.arp": "アルペジエーター",
                "fx.tab.humanize": "ヒューマナイズ",
                "fx.tab.quantize": "クオンタイズ",
                "fx.tab.chords": "コード",
                "fx.arp.pattern": "パターン:",
                "fx.arp.rate": "レート (拍):",
                "fx.arp.octave": "オクターブ範囲:",
                "fx.arp.gate": "ゲート:",
                "fx.hum.timing": "タイミング揺らぎ (拍):",
                "fx.hum.velocity": "ベロシティ揺らぎ:",
                "fx.hum.duration": "長さ揺らぎ (拍):",
                "fx.q.grid": "グリッド (拍):",
                "fx.q.strength": "強度:",
                "fx.chord.type": "コードタイプ:",
                "fx.chord.voicing": "ヴォイシング:",
                "fx.chord.vel_scale": "ベロシティ比率:",
                "fx.apply": "適用",
                "fx.cancel": "キャンセル",
                # Melody Dialog
                "gen.tab.melody": "メロディ",
                "gen.tab.bass": "ベースライン",
                "gen.root": "ルート音:",
                "gen.scale": "スケール:",
                "gen.bars": "小節:",
                "gen.note_range": "音域:",
                "gen.to": "~",
                "gen.stepwise_bias": "ステップ傾向:",
                "gen.velocity": "ベロシティ:",
                "gen.seed": "シード:",
                "gen.random": "ランダム",
                "gen.progression": "コード進行:",
                "gen.pattern": "パターン:",
                "gen.track": "トラック:",
                "gen.generate": "生成",
                "gen.cancel": "キャンセル",
            },
            "ko": {
                "app.title": "사이버 琴仙",
                "app.subtitle": "Cyber Qin Xian",
                "nav.live": "연주 모드",
                "nav.library": "라이브러리",
                "nav.editor": "시퀀서",
                "sidebar.credit": "Edmond Virelle",
                "sidebar.ff14": "FF14: Aimant Virelle",
                "sidebar.wwm": "연운십육성: 葉微雨",
                "sidebar.vtuber": "VTuber: Edmond Virelle",
                "sidebar.support": "Ko-fi 후원하기",
                "sidebar.version": "v{version}",
                "live.title": "연주 모드",
                "live.desc": "MIDI 장치를 연결하고 실시간으로 연주하세요.",
                "live.midi_device": "MIDI 장치",
                "live.refresh": "새로고침",
                "live.connect": "연결",
                "live.disconnect": "연결 끊기",
                "live.mapping": "키 매핑",
                "live.transpose": "조옮김",
                "live.auto_tune": "자동 보정",
                "live.record": "녹음",
                "live.stop_record": "녹음 중지",
                "live.recording": "녹음 중...",
                "live.log": "이벤트 로그",
                "live.status.connected": "연결됨: {port}",
                "live.status.disconnected": "연결 안 됨",
                "lib.title": "라이브러리",
                "lib.desc": "MIDI 파일을 가져오고 더블 클릭하거나 재생 버튼을 누르세요.",
                "lib.search": "검색...",
                "lib.import": "+ MIDI 가져오기",
                "lib.col.num": "#",
                "lib.col.title": "제목",
                "lib.col.duration": "시간",
                "lib.empty.title": "가져온 MIDI 파일 없음",
                "lib.empty.sub": "시작하려면 '+ MIDI 가져오기'를 클릭하세요",
                "editor.title": "시퀀서",
                "editor.desc": "피아노 건반을 클릭하여 음표 입력, 타임라인에서 편집.",
                "editor.record": "● 녹음",
                "editor.play": "▶ 재생",
                "editor.stop": "■ 정지",
                "editor.save": "저장",
                "editor.import": "가져오기",
                "editor.export": "내보내기",
                "editor.undo": "실행 취소 (Ctrl+Z)",
                "editor.redo": "다시 실행 (Ctrl+Y)",
                "editor.clear": "모두 지우기",
                "editor.pencil": "✎ 연필",
                "editor.help": "도움말",
                "editor.duration": "음표 길이",
                "editor.time_sig": "박자",
                "editor.bpm": "BPM",
                "editor.snap": "스냅",
                "editor.velocity": "벨로시티",
                "editor.shortcuts": "⌨ 단축키",
                "editor.note_count": "{notes} 음표 · {bars} 마디",
                "player.repeat.off": "반복 끔",
                "player.repeat.one": "한 곡 반복",
                "player.repeat.all": "전체 반복",
                "scheme.wwm_36.name": "연운십육성 36키",
                "scheme.wwm_36.desc": "3×12 배열: ZXC / ASD / QWE 행, Shift/Ctrl 로 변화표",
                "scheme.ff14_37.name": "FF14 37키",
                "scheme.ff14_37.desc": "3×12 다이어토닉: 숫자(저) / QWER(중) / ASDF(고), Ctrl=변화표",
                "scheme.generic_24.name": "범용 24키",
                "scheme.generic_24.desc": "2×12 배열: ZXC 행 + QWE 행, Shift/Ctrl 로 변화표",
                "scheme.generic_48.name": "범용 48키",
                "scheme.generic_48.desc": "4×12 배열: 숫자행 / ZXC / ASD / QWE, 4 옥타브",
                "scheme.generic_88.name": "범용 88키",
                "scheme.generic_88.desc": "8×11 배열: Shift/Ctrl 다층 조합, 풀 피아노 범위",
                "lib.sort.default": "기본 순서",
                "lib.sort.name": "이름",
                "lib.sort.bpm": "BPM",
                "lib.sort.notes": "음표 수",
                "lib.sort.duration": "시간",
                "live.transpose.suffix": " 옥타브",
                "player.no_track": "트랙 미로드",
                "player.speed": "속도",
                "player.countdown": "준비 중... {n}",
                "player.switch_window": "게임 창으로 전환",
                "player.play": "재생 / 일시정지 (Space)",
                "player.pause": "일시정지",
                "player.stop": "정지",
                "player.prev": "이전 곡 (Ctrl+←)",
                "player.next": "다음 곡 (Ctrl+→)",
                "player.repeat.mode.off": "반복: 끔",
                "player.repeat.mode.all": "반복: 전체",
                "player.repeat.mode.one": "반복: 한 곡",
                "editor.pause": "\u23f8 일시정지",
                "editor.resume": "\u25b6 재개",
                # New features
                "editor.arrange": "어레인지",
                "editor.fx": "이펙트",
                "editor.fx.label": "\u2728 이펙트",
                "editor.fx.tooltip": "MIDI 이펙트: 아르페지에이터, 휴머나이즈, 퀀타이즈, 코드 생성",
                "editor.generate": "생성",
                "editor.generate.label": "\ud83c\udfb2 생성",
                "editor.generate.tooltip": "AI 작곡: 멜로디와 베이스라인 자동 생성",
                "editor.sidebar.tooltip": "사이드바 전환: 트랙 패널과 피치 눈금자 표시/숨기기",
                "editor.ghost": "고스트",
                "editor.automation": "오토메이션",
                "editor.score": "악보",
                "nav.practice": "연습",
                "practice.title": "연습 모드",
                "practice.desc": "라이브러리에서 곡을 선택하고 '연습' 버튼을 클릭하세요. 위에서 음표가 내려오면 금색 선에서 정확히 키를 눌러 점수를 획득하세요.",
                "practice.score": "점수",
                "practice.accuracy": "정확도",
                "practice.combo": "콤보",
                "practice.start": "연습 시작",
                "practice.stop": "정지",
                "practice.mode.midi": "MIDI 키보드",
                "practice.mode.keyboard": "PC 키보드",
                "practice.scheme": "키 레이아웃",
                "live.visualizer": "비주얼라이저",
                "lib.metadata.title": "트랙 정보",
                "lib.metadata.artist": "아티스트",
                "lib.metadata.game": "게임",
                "lib.metadata.difficulty": "난이도",
                "lib.metadata.tags": "태그",
                "lib.metadata.source": "출처",
                "lib.metadata.description": "설명",
                "lib.metadata.save": "저장",
                "lib.metadata.cancel": "취소",
                "lib.practice": "연습",
                "lib.edit_metadata": "정보 편집",
                "lib.export_bundle": "번들 내보내기",
                "lib.import_bundle": "번들 가져오기",
                "lib.play": "재생",
                "lib.edit": "시퀀서에서 편집",
                "lib.remove": "제거",
                "lib.col.artist": "아티스트",
                "lib.col.game": "게임",
                "lib.col.difficulty": "난이도",
                # FX Dialog
                "fx.tab.arp": "아르페지에이터",
                "fx.tab.humanize": "휴머나이즈",
                "fx.tab.quantize": "퀀타이즈",
                "fx.tab.chords": "코드",
                "fx.arp.pattern": "패턴:",
                "fx.arp.rate": "속도 (박):",
                "fx.arp.octave": "옥타브 범위:",
                "fx.arp.gate": "게이트:",
                "fx.hum.timing": "타이밍 흔들림 (박):",
                "fx.hum.velocity": "벨로시티 흔들림:",
                "fx.hum.duration": "길이 흔들림 (박):",
                "fx.q.grid": "그리드 (박):",
                "fx.q.strength": "강도:",
                "fx.chord.type": "코드 유형:",
                "fx.chord.voicing": "보이싱:",
                "fx.chord.vel_scale": "벨로시티 비율:",
                "fx.apply": "적용",
                "fx.cancel": "취소",
                # Melody Dialog
                "gen.tab.melody": "멜로디",
                "gen.tab.bass": "베이스라인",
                "gen.root": "루트 음:",
                "gen.scale": "스케일:",
                "gen.bars": "마디:",
                "gen.note_range": "음역:",
                "gen.to": "~",
                "gen.stepwise_bias": "순차진행 편향:",
                "gen.velocity": "벨로시티:",
                "gen.seed": "시드:",
                "gen.random": "랜덤",
                "gen.progression": "코드 진행:",
                "gen.pattern": "패턴:",
                "gen.track": "트랙:",
                "gen.generate": "생성",
                "gen.cancel": "취소",
            },
        }

    @property
    def current_language(self) -> str:
        return self._current_lang

    def set_language(self, lang_code: str) -> None:
        """Change current language and emit signal."""
        if lang_code in LANGUAGES and lang_code != self._current_lang:
            self._current_lang = lang_code
            self.language_changed.emit()

    def tr(self, key: str, **kwargs) -> str:  # type: ignore[override]
        """Translate key to current language. Returns key if not found."""
        lang_data = self._data.get(self._current_lang, {})
        text = lang_data.get(key)

        if text is None:
            # Fallback to English
            text = self._data.get("en", {}).get(key, key)

        try:
            return text.format(**kwargs)
        except (KeyError, ValueError):
            return text


# Global singleton instance
translator: Translator = Translator()
